### ISSUE TITLE
Test ads keep showing

### ISSUE THREAD

**Issue by badar-alkalbani** [YoYoGames/GMEXT-AdMob#10]
I use Admob extension but test ads keep showing even I put my app Admob codes! How to solve that please? I am using the latest Ide and runtime, Thanks

**Comment by DiasFranciscoA** [comment]
To display live ads in your application, you first have to ensure that you've followed all the necessary steps and considerations. Here are a few things you can do to try and solve this problem:

1. **Review Your App's Status**: The approval process can take a bit of time. You should check your AdMob account to confirm that your application and ad unit have been approved and activated.

2. **Replace Test Ad Unit ID with Live Ad Unit ID**: When testing your app, you should use a test ad unit ID to avoid violating AdMob policies. However, once testing is complete, you must replace the test ad unit ID with your own ad unit ID in your code.

3. **Wait for the Ads**: Sometimes, it might take a few hours for the ads to start serving after you've inserted the Ad Unit ID. This is especially true if your app or ad unit is new.


Some extra considerations:

- Check your AdMob account for any notification or alert. Sometimes, issues such as policy violation or unpaid balance can prevent your ads from being shown.
- Ensure that your device or emulator has Google Play services installed: AdMob depends on Google Play services, which is not available on all devices and emulators.


The problem you're facing is likely due to a misconfiguration within the Google Dashboard. Unfortunately, our support does not extend to this issue. However, I encourage you to seek assistance from the community on the forums. They're usually very supportive and may be able to provide the guidance you require.
