### ISSUE TITLE
The Pangle extension doesn't work on iOS.

### ISSUE THREAD

**Issue by KBeeeR** [YoYoGames/GMEXT-AdMob#11]
Hello,
The Pangle extension doesn't work on iOS.
The game crashed on startup.

**Comment by DiasFranciscoA** [comment]
@KBeeeR @FuseGamesLLC

Please note that Pangle serves as a mediator and it's not mandatory to enable it for your AdMob project to function properly. If you intend to use Pangle as a mediator, you'll need to configure an account with them first.

Additionally, keep in mind that Pangle might not be accepted in certain markets, including Japan and India. Unfortunately, we have limited control over such market-specific restrictions.

**Comment by TaylorDale** [comment]
This is incredibly specific - I believe Pangle is also causing a crash on iOS for one of my games.

iOS17 works fine, but all versions bellow, immediate crash on admob init. I can call the consent functions prior just fine. I'm also using Pangle + Same Google ads SDK version in other non-gm apps and it does not cause an issue.

**Comment by patrickrocheyoyo** [comment]
Pangle isn't an extension but it's a mediator for AdMob. There's also issues that may appear in simulations rather than on real devices, so please check on real devices. This issue is likely region exclusive so there's not much we can do to assist here. 

We're planning an update to AdMob in the near future that might help with this. 

If this is still an issue after this update, please open a new issue.
