### ISSUE TITLE
[NOT A BUG] AdMob cocoapods with XCode 15 + phantom runner async_load (runner bug)

### ISSUE THREAD

**Issue by MHG-Works** [YoYoGames/GMEXT-AdMob#15]
Hi, 

I'm still testing AdMob issues on iOS, and it seems the Google Admob extension, and specifically the Yoyo example project on the marketplace, shows a massive list of warnings in XCode, and also throws an error. I have attached a logfile containing all those warnings, as well as a snapshot of the error. IDE and Runtime are both the LATEST, XCode and macOS updates also applied already. Note that I have un-installed cocoapods and re-installed it also. Cocoapods is enabled and minimum target build setting is 16.1. For the DerivedData warnings, I tried clearing the DerivedData folder inside the Libraries > Developer > XCode folder, but the warnings persist anyway.

Would kindly ask the admob extension, using Yoyo's own example project even, be tested for these issues. Again, please see attached warnings log (file is called "Build Google_AdMob_2023-09-24T11-02-19.txt"), and error snapshot, which were produced by Yoyo's example project from the marketplace.

Thanks.

[Build Google_AdMob_2023-09-24T11-02-19.txt](https://github.com/YoYoGames/GMEXT-AdMob/files/12709099/Build.Google_AdMob_2023-09-24T11-02-19.txt)

![IMG_0031](https://github.com/YoYoGames/GMEXT-AdMob/assets/145086729/2a6cb8b2-abdb-4f64-9080-3faf7107aa97)

**Comment by DiasFranciscoA** [comment]
Hello,

Thank you for your report and patience.

After reviewing the details you provided, this ticket will be closed as it does not pertain to a bug with the extension itself. The issues you have described seem to be associated with:

The most recent release of XCode, version 15, especially affecting projects dependent on cocoapods. We are aware of this issue, and an internal fix has already been implemented. This fix will be included in the upcoming hotfix/release.

The demo experiences crashes due to an invalid ds_map error, a known issue with the runner that occasionally triggers “phantom” asynchronous events with invalid maps at random execution points, predominantly when the app is minimized and then restored. A fix for this has also been developed internally and will be available in the next hotfix|release.

NOTE: We have noted the increased number of warnings the AdMob extension triggers during compilation. We plan to address this at a later stage as they do not impact the functionality of the extension. However, if you are comfortable and would like to contribute to our source code to resolve these issues, we welcome you to do so with a Pull Request. We have open-sourced the extensions specifically to encourage community involvement in the development process.

We understand the inconvenience caused and appreciate your understanding. Please watch for the upcoming releases, and do check back with us if the issues persist post-update.

Best Regards,
Francisco Dias
