### ISSUE TITLE
[ISSUE] [RUNNER] [XCODE15] fix for the cocoapods issue on new version of XCode (DT_TOOLCHAIN_DIR)

### ISSUE THREAD

**Issue by MHG-Works** [YoYoGames/GMEXT-AdMob#18]
I just downloaded xcode 15, which had been released in September 18 apparently, to see if the Google Admob Yoyo project would work. Unfortunately, it didn't. MacOS is Ventura 13.6, not the recent release Sonoma. GameMaker IDE is 2023.8.0.98 and Runtime is v2023.8.1.148.

I have attached  the logfile to show what errors xcode produced.

Also, don't want to be that guy, but it's almost been two months since Admob on Game Maker last worked correctly on iOS. Seriously hoping something can be done about these issues as I can't push any update until it starts woking again.

[Build Google_AdMob_2023-10-03T10-05-10.txt](https://github.com/YoYoGames/GMEXT-AdMob/files/12794074/Build.Google_AdMob_2023-10-03T10-05-10.txt)

**Comment by DiasFranciscoA** [comment]
Hello, and thank you for connecting with us!

We acknowledge the problem with XCode 15, and it's currently recognized as a known issue with the Runner. We have scheduled a fix for this in the upcoming LTSr2 and the hotfix planned for the August 2023 release. It’s worth noting that this issue is not related to the AdMob extension.

Regarding the AdMob issues you’ve experienced for the past two months, could you please provide us with more specific details? Understanding the exact issues you're facing will enable us to assist you more effectively. For reference, our team has been able to successfully run the demo project and proceed with tests. Your additional input will be immensely valuable in ensuring that updates and potential fixes align with the challenges you're experiencing.

We appreciate your contribution to enhancing our platform and look forward to assisting you further!

Feel free to adjust as needed to make sure it aligns with your communication style and any additional information you might want to convey!

**Comment by MHG-Works** [comment]
Thanks @DiasFranciscoA for the prompt reply.

Hoping the hotfix gets released soon. 

For the issues I've been experiencing with AdMob, I opened the following issues:

[https://github.com/YoYoGames/GMEXT-AdMob/issues/14](url)

[https://github.com/YoYoGames/GMEXT-AdMob/issues/15](url)

But they were closed without the issue being actually resolved.

I'm also not sure how it is that your team is not running into any problems, but that there is still apparently an issue with the Runner and with xcode 15 itself.

So far, building the app with the AdMob extension included has only produced errors, with new errors being produced that weren't being produced before, and the old ones magically disappearing. Very odd behavior. 

In any case, as I mentioned in an earlier issue thread, I will have to continue posting an issue that comes up if xcode still fails to build the app with the AdMob extension in the project (either my own or the Yoyo example project). Hoping the hotfix comes soon, and when it does, it finally puts the issues to rest.

**Comment by DiasFranciscoA** [comment]
Then the only issue you are experiencing at the moment is the XCode15 one when using cocoapods with error messages regarding `DT_TOOLCHAIN_DIR`, is that it?

**Comment by MHG-Works** [comment]
I wasn't aware xcode 15 was released in mid September so I had been using the most recent version of xcode 14.3 up until today. I experienced the `DT_TOOLCHAIN_DIR` issue only today after updating to xcode 15, so this issue is possibly only limited to xcode 15, so yes to answer your question. 

But the previous two issues (undefined symbol errors and phantom runner) I opened were happening with the most recent versions of xcode v14.x, but only after updating Yoyo AdMob extension to v.1.2.3 and with GM updated to IDE 8.0.99 / Runtime 8.0.145 (latest at the time). This is somewhere mid August. Before that, there were no issues and I successfully managed to push an iOS update with the Admob extension around early August without any problems. So either the Admob extension or GameMaker (runner) itself screwed something up, likely the latter if, as you say, there is a problem with the runner, and not with the extension.

Right now, it looks like there is an update to xcode 15 just today (15.1). But it's beta, and I'd rather see a hotfix for Admob or an update to the runner - somewhat doubting updates to xcode will resolve the issue at this point.

**Comment by DiasFranciscoA** [comment]
The problem you are experiencing is not related to the AdMob extension so there won't be an hotfix associated with this, there are indeed several fixes in the runner itself that will get to either a possible 2023.8.2 or LTSr2.

**Comment by MHG-Works** [comment]
Well, the most recent version of the runner is Version 2023.8.1.148. So as soon as this is updated, I will test again and post the results. If all works well, I'll close the issue. If not, I'll post a logfile. Not sure I'll be updating xcode, unless this becomes a requirement.

**Comment by MHG-Works** [comment]
@DiasFranciscoA  Latest version of runner has fixed the issue. Closing. Thanks for your input!
