### ISSUE TITLE
ios banner_move strange working

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-AdMob#38]
ios banner_move strange working

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out regarding the issues you're experiencing with `AdMob_Banner_Move`. In order to assist you effectively, I'd appreciate it if you could provide some additional information:

Description of the Issue:
Please specify the specific problems or errors you're encountering with the `AdMob_Banner_Move` implementation. What type of banner are you using? What is the strange behavior? Any details or error messages you can provide will help us diagnose the issue more accurately.

Android Version:
Knowing the version of Android you're using will be helpful for troubleshooting. Could you please provide this information?

Reproducible Steps:
It would greatly assist us in diagnosing the issue if you could outline the steps to reproduce the problem. This will allow us to replicate the issue on our end and identify any potential causes.

Demo Project Check:
Have you tried running the demo project to see if the ads work there? If the ads function correctly in the demo project but not in your implementation, it's possible that there may be a problem with your setup or implementation.

Please provide the requested information, and feel free to include any additional details or logs that you think may be relevant. We're here to help and will do our best to assist you in resolving this issue.
