### ISSUE TITLE
[ANSWERED] Issue with mediation: AdMobPangle

### ISSUE THREAD

**Issue by SantiFerre** [YoYoGames/GMEXT-AdMob#5]
I'm using Android with x86 architecture in the Android emulator. When I run my game (including the example project), I see the following message: "Unable to find library for this devices architecture, which is i686, ensure you have included the correct architecture in your APK"

> ![image](https://github.com/YoYoGames/GMEXT-AdMob/assets/32647282/57241920-8ff3-4e95-bd4a-b7318288b7bd)

I became frustrated trying to find the cause of this issue, but when I removed some extensions from my project, I discovered the problem. The mediation extension "AdMobPangle" doesn't work with x86. Moreover, while exploring the folders, I noticed numerous unnecessary files in each mediation folder, including multiple duplicates of the file "AdMobUnityAdsXX.yy."

I don't quite understand what mediation extensions are for exactly. Can I do without the one that is causing problems for me?

**Comment by DiasFranciscoA** [comment]
Thank you for bringing this issue to our attention. We apologize for any frustration caused by the "AdMobPangle" extension not supporting x86 architecture in the Android emulator. To address your concerns, we would like to provide the following information:

1. **"AdMobPangle" Extension and x86 Architecture**: The "AdMobPangle" extension, as you mentioned, does not currently support x86 architecture. This limitation means that it cannot be used specifically for the x86 target. We recommend considering alternative extensions or approaches if you require x86 compatibility in your project.

2. **Duplicates of "AdMobUnityAdsXX.yy"**: The presence of multiple duplicate files named "AdMobUnityAdsXX.yy" within the mediation folders does not pose any significant issues. These duplicates are ignored during the build process, and they do not affect the functionality of the extension. Therefore, you can safely disregard them.

3. **Mediation Extensions**: Mediation extensions, including "AdMobPangle," play a crucial role in enabling ad mediation within your project. Ad mediation allows you to leverage multiple ad networks to maximize your revenue potential by displaying ads from different sources. However, **it is not mandatory to use mediation extensions** if they do not align with your specific requirements or cause compatibility issues. You can choose to work solely with the core "AdMob" extension or explore other mediation options that better suit your needs.

We hope this clarifies the situation for you. If you have any further questions or need additional assistance, please feel free to ask. We are here to help.

Best regards,
Francisco Dias

**Comment by SantiFerre** [comment]
Thank you for your answer and explanations! I think that I'm going to disable x86 build in my game and update the emulator's architecture to arm64.
