### ISSUE TITLE
Long black screen before returning to game, after Ad is finished playing.

### ISSUE THREAD

**Issue by samuelrl86** [YoYoGames/GMEXT-AdMob#6]
I am using the Rewards ad.  After the Ad is done playing and the (x) at the top right of the ad video is pressed, there is a 5 second black screen delay before returning to the game.

Additional info which may help :
My texture pages are set to 2048, and when I reduce them to 1024 then black screen is reduced by half.  When I reduce the texture pages to 512 the return to game is instant.

**Comment by vitito93** [comment]
It was solved for me by putting all the texture groups as type "QOI"

**Comment by DiasFranciscoA** [comment]
Hello @vitito93,

We appreciate your patience and your effort to report the issue you're experiencing during the transition from the Rewards ad back to your game. We understand how a delay like this can hinder your gaming experience.

After closely examining the situation, it appears that this delay is linked to how the game handles textures, specifically in relation to our OpenGL implementation. We're currently required to flush all textures when changing focus due to the OpenGL constraints in our system.

We deeply regret the inconvenience this has caused you. As a potential workaround for now, you may consider switching the texture groups to "QOI", which you have already done. Although this will not resolve the underlying problem, it can improve the pack and unpack times, potentially speeding up the transition. Please be aware, however, that the core issue of flushing and reloading all textures remains.

Should you have further questions or encounter other issues, we are always available to assist. Your understanding in this matter is greatly appreciated.

Best Regards,
Francisco Dias
